language: cpp
os: linux
compiler: gcc

addons:
  apt:
    packages:
    - lcov

before_script:
- cd skeleton-project

script:
- cd 3PL
- bash build_3PL.sh
- cd ..
  # - cd MyAwesomeLibrary
  # - bash config.sh
  # - cd ..

after_success:
  # - cd MyAwesomeLibrary 
  # - bash get_converage.sh

# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
# - bash <(curl -s https://codecov.io/bash) -f ./skeleton-project/MyAwesomeLibrary/coverage/AWESOME_COV.info || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - ackirby88@gmail.com
