language: cpp
os: linux
compiler: gcc

addons:
  apt:
    packages:
    - lcov

before_script:
- cd skeleton-project

script:
- cd 3PL
- bash build_3PL.sh
- cd ..
- cd MyAwesomeLibrary
- bash config.sh
- cd ..

after_success:
- cd MyAwesomeLibrary 
- bash coverage.sh
# Uploading to CodeCov
- bash <(curl -s https://codecov.io/bash) -f ./coverage/AWESOME_COV.info || echo "Codecov did not collect coverage reports"
- cd ..

notifications:
  email:
    - ackirby88@gmail.com
